application: many-hats-studio
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /media
  static_dir: media

- url: /css
  static_dir: media/css

- url: /img
  static_dir: media/img

- url: /js
  static_dir: media/js

- url: /fonts
  static_dir: media/fonts

- url: .*
  script: main.py

libraries:
- name: jinja2
  version: latest